# SFT model on synthetic reasoning traces 

torchrun --nnodes=1 --nproc_per_node=8 -m verl.trainer.fsdp_sft_trainer \
    data.train_files=bigcodebench_data/bigcodebench_hard_interleaved_coding_dataset_train.parquet \
    data.val_files=bigcodebench_data/bigcodebench_hard_interleaved_coding_dataset_test.parquet \
    data.train_batch_size=8 \
    data.prompt_key=question \
    data.response_key=answer \
    data.micro_batch_size_per_gpu=1 \
    model.partial_pretrain=Qwen/Qwen3-8B \
    trainer.project_name=interleaved-sft \
    trainer.experiment_name=interleaved-sft-Qwen3-8B_bigcodebench \
    trainer.total_epochs=200 \
    trainer.logger=['console','wandb'] \
    trainer.save_freq=200 \
    use_remove_padding=True \
    ulysses_sequence_parallel_size=4 



# base interleaving
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files=verl/data/bigcodebench/train_with_unit_tests.parquet \
 data.val_files=verl/data/bigcodebench/val_with_unit_tests.parquet \
 data.train_batch_size=32 \
 data.val_batch_size=32 \
 data.max_prompt_length=3096 \
 data.max_response_length=2000 \
 actor_rollout_ref.model.path=checkpoints/interleaved-sft/interleaved-sft-Qwen3-8B_bigcodebench/global_step_500 \
 critic.model.path=checkpoints/interleaved-sft/interleaved-sft-Qwen3-8B_bigcodebench/global_step_500 \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=32 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.actor.use_kl_loss=True \
 actor_rollout_ref.actor.kl_loss_coef=0.001 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
 actor_rollout_ref.rollout.disable_log_stats=False \
 actor_rollout_ref.rollout.n=8 \
 actor_rollout_ref.rollout.temperature=0.7 \
 actor_rollout_ref.rollout.template_type=interleave \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 critic.optim.lr=1e-6 \
 critic.ppo_micro_batch_size_per_gpu=4 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 trainer.val_before_train=False \
 trainer.default_hdfs_dir=null \
 trainer.n_gpus_per_node=8 \
 trainer.nnodes=1 \
 trainer.save_freq=50 \
 trainer.test_freq=50 \
 trainer.logger=['console','wandb'] \
 trainer.project_name=verl \
 trainer.experiment_name=bcb_interleave_2k_rl \
 trainer.validation_data_dir=val_results \
 trainer.rollout_data_dir=rollout_results \
 trainer.max_actor_ckpt_to_keep=2 \
 trainer.max_critic_ckpt_to_keep=2 \
 trainer.total_training_steps=1000 \
 trainer.autorater_service_url="http://10.128.0.30:81" 2>&1 | tee verl_demo.log

# longer sequence length
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files=verl/data/bigcodebench/train_with_unit_tests.parquet \
 data.val_files=verl/data/bigcodebench/val_with_unit_tests.parquet \
 data.train_batch_size=16 \
 data.val_batch_size=16 \
 data.max_prompt_length=3096 \
 data.max_response_length=4000 \
 actor_rollout_ref.model.path=checkpoints/interleaved-sft/interleaved-sft-Qwen3-8B_bigcodebench/global_step_500 \
 critic.model.path=checkpoints/interleaved-sft/interleaved-sft-Qwen3-8B_bigcodebench/global_step_500 \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=16 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.actor.use_kl_loss=True \
 actor_rollout_ref.actor.kl_loss_coef=0.001 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
 actor_rollout_ref.rollout.disable_log_stats=False \
 actor_rollout_ref.rollout.n=8 \
 actor_rollout_ref.rollout.temperature=0.7 \
 actor_rollout_ref.rollout.template_type=interleave \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 critic.optim.lr=1e-6 \
 critic.ppo_micro_batch_size_per_gpu=4 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 trainer.val_before_train=False \
 trainer.default_hdfs_dir=null \
 trainer.n_gpus_per_node=8 \
 trainer.nnodes=1 \
 trainer.save_freq=50 \
 trainer.test_freq=50 \
 trainer.logger=['console','wandb'] \
 trainer.project_name=verl \
 trainer.experiment_name=bcb_interleave_4k_rl \
 trainer.validation_data_dir=val_results \
 trainer.rollout_data_dir=rollout_results \
 trainer.max_actor_ckpt_to_keep=2 \
 trainer.max_critic_ckpt_to_keep=2 \
 trainer.total_training_steps=1000 \
 trainer.autorater_service_url="http://10.128.0.30:81" 2>&1 | tee verl_demo.log

# train without interleaving 
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files=verl/data/bigcodebench/train_with_unit_tests.parquet \
 data.val_files=verl/data/bigcodebench/val_with_unit_tests.parquet \
 data.train_batch_size=32 \
 data.val_batch_size=32 \
 data.max_prompt_length=3096 \
 data.max_response_length=2000 \
 actor_rollout_ref.model.path=Qwen/Qwen3-8B \
 critic.model.path=Qwen/Qwen3-8B \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=32 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.actor.use_kl_loss=True \
 actor_rollout_ref.actor.kl_loss_coef=0.001 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
 actor_rollout_ref.rollout.disable_log_stats=False \
 actor_rollout_ref.rollout.n=8 \
 actor_rollout_ref.rollout.temperature=0.7 \
 actor_rollout_ref.rollout.template_type=default \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 critic.optim.lr=1e-6 \
 critic.ppo_micro_batch_size_per_gpu=4 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 trainer.val_before_train=False \
 trainer.default_hdfs_dir=null \
 trainer.n_gpus_per_node=8 \
 trainer.nnodes=1 \
 trainer.save_freq=50 \
 trainer.test_freq=50 \
 trainer.logger=['console','wandb'] \
 trainer.project_name=verl \
 trainer.experiment_name=bcb_base_2k_rl \
 trainer.validation_data_dir=val_results \
 trainer.rollout_data_dir=rollout_results \
 trainer.max_actor_ckpt_to_keep=2 \
 trainer.max_critic_ckpt_to_keep=2 \
 trainer.total_training_steps=1000 \
 trainer.autorater_service_url="http://10.128.0.30:81" 2>&1 | tee verl_demo.log

# train without interleaving 4k
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files=verl/data/bigcodebench/train_with_unit_tests.parquet \
 data.val_files=verl/data/bigcodebench/val_with_unit_tests.parquet \
 data.train_batch_size=16 \
 data.val_batch_size=16 \
 data.max_prompt_length=3096 \
 data.max_response_length=4000 \
 actor_rollout_ref.model.path=Qwen/Qwen3-8B \
 critic.model.path=Qwen/Qwen3-8B \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=16 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.actor.use_kl_loss=True \
 actor_rollout_ref.actor.kl_loss_coef=0.001 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
 actor_rollout_ref.rollout.disable_log_stats=False \
 actor_rollout_ref.rollout.n=8 \
 actor_rollout_ref.rollout.temperature=0.7 \
 actor_rollout_ref.rollout.template_type=default \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 critic.optim.lr=1e-6 \
 critic.ppo_micro_batch_size_per_gpu=4 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 trainer.val_before_train=False \
 trainer.default_hdfs_dir=null \
 trainer.n_gpus_per_node=8 \
 trainer.nnodes=1 \
 trainer.save_freq=50 \
 trainer.test_freq=50 \
 trainer.logger=['console','wandb'] \
 trainer.project_name=verl \
 trainer.experiment_name=bcb_base_rl \
 trainer.validation_data_dir=val_results \
 trainer.rollout_data_dir=rollout_results \
 trainer.max_actor_ckpt_to_keep=2 \
 trainer.max_critic_ckpt_to_keep=2 \
 trainer.total_training_steps=1000 \
 trainer.autorater_service_url="http://10.128.0.30:81" 2>&1 | tee verl_demo.log


# eval base model
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files=verl/data/bigcodebench/train_with_unit_tests.parquet \
 data.val_files=verl/data/bigcodebench/val_with_unit_tests.parquet \
 data.train_batch_size=32 \
 data.val_batch_size=32 \
 data.max_prompt_length=3096 \
 data.max_response_length=2000 \
 actor_rollout_ref.model.path=Qwen/Qwen3-8B \
 critic.model.path=Qwen/Qwen3-8B \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=32 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.actor.use_kl_loss=True \
 actor_rollout_ref.actor.kl_loss_coef=0.001 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
 actor_rollout_ref.rollout.disable_log_stats=False \
 actor_rollout_ref.rollout.n=8 \
 actor_rollout_ref.rollout.temperature=0.7 \
 actor_rollout_ref.rollout.template_type=default \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 critic.optim.lr=1e-6 \
 critic.ppo_micro_batch_size_per_gpu=4 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 trainer.val_before_train=False \
 trainer.default_hdfs_dir=null \
 trainer.n_gpus_per_node=8 \
 trainer.nnodes=1 \
 trainer.save_freq=200 \
 trainer.test_freq=50 \
 trainer.logger=['console','wandb'] \
 trainer.project_name=verl \
 trainer.experiment_name=bcb_base_eval \
 trainer.validation_data_dir=val_results \
 trainer.rollout_data_dir=rollout_results \
 trainer.max_actor_ckpt_to_keep=5 \
 trainer.max_critic_ckpt_to_keep=5 \
 trainer.total_training_steps=1000 \
 trainer.autorater_service_url="http://10.128.0.30:81" \
 trainer.val_before_train=True \
 trainer.val_only=True 2>&1 | tee verl_demo.log

# eval SFT model
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files=verl/data/bigcodebench/train_with_unit_tests.parquet \
 data.val_files=verl/data/bigcodebench/val_with_unit_tests.parquet \
 data.train_batch_size=32 \
 data.val_batch_size=32 \
 data.max_prompt_length=3096 \
 data.max_response_length=2000 \
 actor_rollout_ref.model.path=checkpoints/interleaved-sft/interleaved-sft-Qwen3-8B_bigcodebench_2/global_step_1000 \
 critic.model.path=checkpoints/interleaved-sft/interleaved-sft-Qwen3-8B_bigcodebench_2/global_step_1000 \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=32 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.actor.use_kl_loss=True \
 actor_rollout_ref.actor.kl_loss_coef=0.001 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
 actor_rollout_ref.rollout.disable_log_stats=False \
 actor_rollout_ref.rollout.n=8 \
 actor_rollout_ref.rollout.temperature=0.7 \
 actor_rollout_ref.rollout.template_type=default \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 critic.optim.lr=1e-6 \
 critic.ppo_micro_batch_size_per_gpu=4 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 trainer.val_before_train=False \
 trainer.default_hdfs_dir=null \
 trainer.n_gpus_per_node=8 \
 trainer.nnodes=1 \
 trainer.save_freq=200 \
 trainer.test_freq=50 \
 trainer.logger=['console','wandb'] \
 trainer.project_name=verl \
 trainer.experiment_name=bcb_interleave_sft_eval \
 trainer.validation_data_dir=val_results \
 trainer.rollout_data_dir=rollout_results \
 trainer.max_actor_ckpt_to_keep=5 \
 trainer.max_critic_ckpt_to_keep=5 \
 trainer.total_training_steps=1000 \
 trainer.autorater_service_url="http://10.128.0.30:81" \
 trainer.val_before_train=True \
 trainer.val_only=True 2>&1 | tee verl_demo.log


# verl/data/knights_and_knaves/test.parquet 

# eval base model on OOD prompts
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files=custom_prompts.parquet \
 data.val_files=custom_prompts.parquet \
 actor_rollout_ref.actor.ppo_mini_batch_size=8 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
 actor_rollout_ref.rollout.template_type=interleave \
 critic.ppo_micro_batch_size_per_gpu=1 \
 data.train_batch_size=8 \
 data.val_batch_size=8 \
 data.max_prompt_length=3096 \
 data.max_response_length=2000 \
 actor_rollout_ref.model.path=Qwen/Qwen3-8B \
 critic.model.path=Qwen/Qwen3-8B \
 trainer.n_gpus_per_node=8 \
 trainer.nnodes=1 \
 trainer.logger=['console','wandb'] \
 trainer.project_name=verl \
 trainer.experiment_name=bigcodebench_base_interleave_rl/ \
 trainer.validation_data_dir=val_results \
 trainer.rollout_data_dir=rollout_results \
 trainer.autorater_service_url="http://10.128.0.30:81" \
 trainer.val_before_train=True \
 trainer.val_only=True 2>&1 | tee verl_demo.log
